[package]
name = "caper"
version = "0.0.1"
authors = ["shockham <samuel.hockham@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/shockham/caper"
homepage = "https://github.com/shockham/caper"
documentation = "https://github.com/shockham/caper"
description = "Small game framework"

[dependencies]
glium = "0.15"
glium_text = { git = "https://github.com/shockham/glium_text" }
time = "0.1"
genmesh = "0.4"
obj = { version = "0.5", features = ["usegenmesh"] }
noise = "0.2"
imgui = { git = "https://github.com/Gekkio/imgui-rs" }

[dev-dependencies]
fps_counter = "0.2"
