[package]
name = "caper"
version = "0.0.1"
authors = ["shockham <samuel.hockham@gmail.com>"]
license = "MIT"

[dependencies]
glium = "*"
glium_text = { git = "https://github.com/tomaka/glium_text.git" } 
time = "*"
genmesh = "*"
obj = { version = "*", features = ["usegenmesh"] }
noise = "*"
imgui = { git = "https://github.com/shockham/imgui-rs" }

[dev-dependencies]
fps_counter = "*"
