[package]
name = "caper"
version = "0.1.0"
authors = ["shockham <samuel.hockham@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/shockham/caper"
homepage = "https://github.com/shockham/caper"
documentation = "https://docs.rs/caper/*/caper/"
description = "Small game framework"

[dependencies]
glium = "0.16"
glium_text = "0.11"
time = "0.1"
genmesh = "0.4"
obj = { version = "0.5", features = ["usegenmesh"] }
noise = "0.2"
imgui = { git = "https://github.com/Gekkio/imgui-rs" } 
fps_counter = "0.2.0"
bincode = "0.6"
rustc-serialize = "0.3"
nphysics3d = "0.5"
nalgebra = "0.9"
ncollide = "0.10"
