[package]
name = "caper"
version = "0.0.1"
authors = ["shockham <samuel.hockham@gmail.com>"]
license = "MIT"

[dependencies]
glium = "0.12"
glium_text = "*"
time = "*"
genmesh = "0.2.1"
obj = "0.2.1"
noise = "*"

[dev-dependencies]
fps_counter = "*"
