[package]
name = "caper"
version = "0.0.1"
authors = ["shockham <samuel.hockham@gmail.com>"]
license = "MIT"

[dependencies]
glium = "*"
glium_text = "*"
genmesh = "*"
clock_ticks = "*"
obj = "*"

[dev-dependencies]
noise = "*"
